name: products deployment

on:
  push:
    branches: [main]

jobs:
  build-push:
    name: Build & Push
    runs-on: self-hosted

    steps:      
      - name: Build image
        run: docker build -t wesha/shopping-products:0.0.0 .

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
        
      - name: Push image
        run: docker push wesha/shopping-products:0.0.0
      
  deploy:
    name: Deploy
    needs: build-push
    runs-on: self-hosted

    steps: 
      - name: check
        run: echo "hooray!"