name: products integration

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: self-hosted
    container: node:17-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: npm install && npm run test

  build-push:
    name: Build & Push
    runs-on: self-hosted

    steps:
      - name: Build image
        run: docker build -t wesha/shopping-products:0.0.0 .

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
        
      - name: Push image
        run: docker push wesha/shopping-products:0.0.0
      