name: products integration

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: self-hosted
    container: node:17-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ls
      