name: products integration

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: self-hosted
    container: node:17-alpine

    steps:
      - name: Run tests
        run: npm install && npm run test
      